In [1]:
# SQLAlchemy
from sqlalchemy import create_engine
import pandas as pd

In [2]:
df=pd.read_csv('..//Outputs/TV_shows_v5.csv')
df

,Unnamed: 0,Title,Year,Age,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney,...,First Air Date,# of Seasons,# of Episodes,Genre,Language,Country,In Production,Origin Network,Similar1,Similar2
0,0,Breaking Bad,2008,18+,9.5,96%,1,0,0,0,...,1/20/2008,5.0,62.0,Drama,en,US,False,AMC,Narcos,Weeds
1,1,Stranger Things,2016,16+,8.8,93%,1,0,0,0,...,7/15/2016,3.0,25.0,Mystery,en,US,True,Netflix,グレイプニル,ひぐらしのなく頃に
2,2,Money Heist,2017,18+,8.4,91%,1,0,0,0,...,5/2/2017,2.0,31.0,Crime,es,ES,True,Netflix,Firefly,This Is Us
3,3,Sherlock,2010,16+,9.1,78%,1,0,0,0,...,7/25/2010,4.0,12.0,Crime,en,GB,False,BBC One,Death in Paradise,The Outsider
4,4,Better Call Saul,2015,18+,8.7,97%,1,0,0,0,...,2/8/2015,6.0,63.0,Comedy,en,US,True,AMC,grown-ish,Joey
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5606,5606,Tut's Treasures: Hidden Secrets,2018,NaN,NaN,NaN,0,0,0,1,...,1/28/2018,1.0,3.0,NaN,en,NaN,NaN,NaN,NaN,NaN
5607,5607,Paradise Islands,2017,NaN,NaN,NaN,0,0,0,1,...,1/1/2017,1.0,3.0,NaN,en,GB,True,National Geographic,NaN,NaN
5608,5608,Wild Russia,2018,NaN,NaN,NaN,0,0,0,1,...,10/15/2018,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5609,5609,Love & Vets,2017,NaN,NaN,NaN,0,0,0,1,...,6/17/2020,2.0,10.0,NaN,en,US,True,Hulu,Merlí,さらざんまい
5610,5610,United States of Animals,2016,NaN,NaN,NaN,0,0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
engine = create_engine("sqlite:///tv_data.sqlite", echo=True)
sqlite_conn = engine.connect()

2020-09-10 19:00:51,188 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2020-09-10 19:00:51,192 INFO sqlalchemy.engine.base.Engine ()
2020-09-10 19:00:51,193 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2020-09-10 19:00:51,194 INFO sqlalchemy.engine.base.Engine ()

In [7]:
sqlite_table='TvShows'
df.to_sql(sqlite_table, sqlite_conn, if_exists='fail')

2020-09-10 19:02:04,691 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("TvShows")
2020-09-10 19:02:04,693 INFO sqlalchemy.engine.base.Engine ()

ValueError: Table 'TvShows' already exists.

In [6]:
engine.execute('SELECT * FROM TvShows LIMIT 5').fetchall()

2020-09-10 19:01:45,396 INFO sqlalchemy.engine.base.Engine SELECT * FROM TvShows LIMIT 5
2020-09-10 19:01:45,397 INFO sqlalchemy.engine.base.Engine ()

[(0, 0, 'Breaking Bad', 2008, '18+', 9.5, '96%', 1, 0, 0, 0, 217.196, 1396.0, 8.6, 5478.0, 9.094, '9/29/2013', '1/20/2008', 5.0, 62.0, 'Drama', 'en', 'US', 0, 'AMC', 'Narcos', 'Weeds'),
 (1, 1, 'Stranger Things', 2016, '16+', 8.8, '93%', 1, 0, 0, 0, 185.468, 66732.0, 8.5, 5502.0, 8.8, '7/4/2019', '7/15/2016', 3.0, 25.0, 'Mystery', 'en', 'US', 1, 'Netflix', 'グレイプニル', 'ひぐらしのなく頃に'),
 (2, 2, 'Money Heist', 2017, '18+', 8.4, '91%', 1, 0, 0, 0, 306.686, 71446.0, 8.4, 9208.0, 7.0, '4/3/2020', '5/2/2017', 2.0, 31.0, 'Crime', 'es', 'ES', 1, 'Netflix', 'Firefly', 'This Is Us'),
 (3, 3, 'Sherlock', 2010, '16+', 9.1, '78%', 1, 0, 0, 0, 72.346, 19885.0, 8.4, 2375.0, 7.2860000000000005, '1/15/2017', '7/25/2010', 4.0, 12.0, 'Crime', 'en', 'GB', 0, 'BBC One', 'Death in Paradise', 'The Outsider'),
 (4, 4, 'Better Call Saul', 2015, '18+', 8.7, '97%', 1, 0, 0, 0, 61.913999999999994, 60059.0, 8.3, 1778.0, 9.25, '4/20/2020', '2/8/2015', 6.0, 63.0, 'Comedy', 'en', 'US', 1, 'AMC', 'grown-ish', 'Joey')]